disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "mhackeroni"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "mhackeroni-stylized-square.webp"
secondaryLogo = "mhackeroni-stylized-square.webp"
description = "Italian CTF team. DEF CON finalists. Cyber. Pasta. Hack-A-Sat 4 Winners."

[params.author]
  name = "mhackeroni"
  email = "info@mhackeroni.it"
  image = "mhackeroni-stylized-square.webp"
  imageQuality = 96
  headline = "Italian CTF team. DEF CON finalists. Cyber. Pasta. Hack-A-Sat 4 Winners."
  location = "Italy"
  bio = "mhackeroni is an Italian CTF team founded in 2018 by a group of friends and security enthusiasts from various academic institutions who merged togheter to sum their streghts and ultimately achieve DEFCON CTF Finals qualification. Certified Satellite Hackers 🛰️ since 2023 :)"
  links = [
    { email = "mailto:info@mhackeroni.it" },
#     { link = "https://link-to-some-website.com/" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
    { bluesky = "https://bsky.app/profile/mhackeroni.bsky.social" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
    { facebook = "https://www.facebook.com/mhackeroni" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/mhackeroni/" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
#     { instagram = "https://instagram.com/username" },
#     { itch-io = "https://username.itch.io" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
    { linkedin = "https://www.linkedin.com/company/mhackeroni-inc/" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { spotify = "https://open.spotify.com/user/userid" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { telegram = "https://t.me/username" },
#     { threads = "https://www.threads.net/@username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
    # { twitter = "https://x.com/mhackeroni" },
    { x-twitter = "https://x.com/mhackeroni" },
#     { whatsapp = "https://wa.me/phone-number" },
    { youtube = "https://www.youtube.com/@mhackeroni" },
#     { ko-fi = "https://ko-fi.com/username" },
#     { codeberg = "https://codeberg.org/username"},
  ]
